openapi: 3.0.0
info:
  title: Acquiring Services API - Open Finance Brasil
  description: |
    Open Finance Brasil Acquiring API – Phase 4.
    API that returns Acquiring information.
  version: 1.0.1
  license:
    name: Apache 2.0
    url: 'https://www.apache.org/licenses/LICENSE-2.0'
tags:
  - name: PersonalAcquiringServices
    description: Operations to obtain Acquiring information for individuals.
  - name: BusinessAcquiringServices
    description: Operations to obtain Acquiring information for legal entities.
paths:
  /personals:
    get:
      tags:
        - PersonalAcquiringServices
      summary: Set of Acquiring information for individuals.
      operationId: getPersonalAcquiringServices
      description: Method to make fees and charges available per services.
      parameters:
        - $ref: '#/components/parameters/page'
        - $ref: '#/components/parameters/pageSize'
      responses:
        '200':
          $ref: '#/components/responses/OKResponseAcquiringServices'
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'
        '405':
          $ref: '#/components/responses/MethodNotAllowed'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/InternalServerError'
        '529':
          $ref: '#/components/responses/SiteIsOverloaded'
  /businesses:
    get:
      tags:
        - BusinessAcquiringServices
      summary: Set of Acquiring information for legal entities.
      operationId: getBusinessAcquiringServices
      description: Method to make fees and charges available per services.
      parameters:
        - $ref: '#/components/parameters/page'
        - $ref: '#/components/parameters/pageSize'
      responses:
        '200':
          $ref: '#/components/responses/OKResponseAcquiringServices'
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'
        '405':
          $ref: '#/components/responses/MethodNotAllowed'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/InternalServerError'
        '529':
          $ref: '#/components/responses/SiteIsOverloaded'
components:
  schemas:
    OKResponseAcquiringServices:
      type: object
      required:
        - data
        - links
        - meta
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/AcquiringServicesContractData'
        links:
          $ref: '#/components/schemas/Links'
        meta:
          $ref: '#/components/schemas/OpenDataMeta'
      additionalProperties: false
    Links:
      type: object
      description: References to other resources of the requested API.
      required:
        - self
      properties:
        self:
          type: string
          format: url
          maxLength: 2000
          description: Full URI that generated the current response.
          example: 'https://api.banco.com.br/open-banking/api/v1/resource'
        first:
          type: string
          format: url
          maxLength: 2000
          description: URI of the first page that originated this list of results. Restriction - Mandatory when it is not the first page of the response
          example: 'https://api.banco.com.br/open-banking/api/v1/resource'
        prev:
          type: string
          format: url
          maxLength: 2000
          description: "URI of the previous page of this list of results. Restriction - Mandatory when it is not the first page of the response"
          example: 'https://api.banco.com.br/open-banking/api/v1/resource'
        next:
          type: string
          format: url
          maxLength: 2000
          description: URI of the next page of this list of results. Restriction - Mandatory when it is not the last page of the response
          example: 'https://api.banco.com.br/open-banking/api/v1/resource'
        last:
          type: string
          format: url
          maxLength: 2000
          description: URI of the last page of this list of results. Restriction - Mandatory when it is not the last page of the response
          example: 'https://api.banco.com.br/open-banking/api/v1/resource'
      additionalProperties: false
    OpenDataMeta:
      type: object
      description: Meta information regarding the requested API.
      required:
        - totalRecords
        - totalPages
      properties:
        totalRecords:
          type: integer
          format: int32
          description: Total number of records in the result
          example: 1
        totalPages:
          type: integer
          format: int32
          description: Total number of pages in the result
          example: 1
      additionalProperties: false
    AcquiringParticipant:
      type: object
      description: Set of information regarding the Open Finance product participant
      required:
        - brand
        - name
        - cnpjNumber
      properties:
        brand:
          type: string
          description: 'Brand name reported by the Open Finance participant. The concept referred to by ''brand'' is essentially a company''s promise to provide a specific series of uniform attributes, benefits, and services to customers.'
          pattern: '[\w\W\s]*'
          maxLength: 80
          example: Organização # Organization
        name:
          type: string
          description: Name of the Open Finance participant.
          pattern: '[\w\W\s]*'
          maxLength: 80
          example: Organização A1 # Organization A1
        cnpjNumber:
          type: string
          description: 'The CNPJ corresponds to the registration number in the National Registry of Legal Entities. Only the CNPJ numbers must be provided, without masking.'
          pattern: '^\d{14}$'
          example: '13456789000112'
        urlComplementaryList:
          type: string
          description: |
            It is expected that the return value, after accessing the ‘urlComplementaryList’ link, must be an array of object with the structure below:

            - ‘name’ with the value contained in the ‘LegalEntityName’ field as registered in the directory;

            - 'cnpjNumber' with the value contained in the CNPJ (‘RegistrationNumber’) corresponding to this institution;

            - Both of string type;

            - Both mandatory.
          maxLength: 1024
          pattern: '^(https?:\/\/)?(www\.)?[-a-zA-Z0-9@:%._\+~#=]{2,256}\.[a-z]{2,6}\b([-a-zA-Z0-9@:%_\+.~#?&\/\/=]*)$'
          example: 'https://empresaa1.com/companies'
      additionalProperties: false
    EnumAcquiringServicesFeeName:
      type: string
      description: |
        Name of the fee charged on the acquiring service, for individuals/legal entities.
          1. Discount Rate in Credit Modality
          2. Discount Rate in Debit Modality
      enum:
        - TAXA_DESCONTO_MODALIDADE_CREDITO # DISCOUNT_RATE_CREDIT_MODALITY
        - TAXA_DESCONTO_MODALIDADE_DEBITO  # DISCOUNT_RATE_DEBIT_MODALITY
      example: TAXA_DESCONTO_MODALIDADE_CREDITO # DISCOUNT_RATE_CREDIT_MODALITY
    EnumAcquiringServicesCode:
      type: string
      description: Acronym of the Fee charged on the reported Acquiring Service.
      enum:
        - MDR_CREDITO # MDR_CREDIT
        - MDR_DEBITO # MDR_DEBIT
      example: MDR_CREDITO # MDR_CREDIT
    EnumAcquiringServicesInterval:
      type: string
      description: Identification of the interval to be displayed.
      enum:
        - 1_FAIXA # 1ST_RANGE
        - 2_FAIXA # 2ND_RANGE
        - 3_FAIXA # 3RD_RANGE
        - 4_FAIXA # 4TH_RANGE
      example: 1_FAIXA # 1ST_RANGE
    Price:
      type: object
      description: '4 ranges of equal size, with their respective medians and customer percentages.'
      required:
        - interval
        - value
        - customerRate
      properties:
        interval:
          $ref: '#/components/schemas/EnumAcquiringServicesInterval'
        value:
          type: string
          example: '0.019800'
          minLength: 8
          maxLength: 8
          pattern: '^\d{1}\.\d{6}$'
          description: Median referring to the debit or credit discount rate for each interval.
        customerRate:
          type: string
          example: '0.019800'
          minLength: 8
          maxLength: 8
          pattern: '^\d{1}\.\d{6}$'
          description: Percentage of customers in each interval.
      additionalProperties: false
    AcquiringServicesContractData:
      type: object
      description: Set of information regarding acquiring information
      required:
        - participant
        - feeName
        - code
        - prices
        - chargingTriggerInfo
        - minimum
        - maximum
      properties:
        participant:
          $ref: '#/components/schemas/AcquiringParticipant'
        feeName:
          $ref: '#/components/schemas/EnumAcquiringServicesFeeName'
        code:
          $ref: '#/components/schemas/EnumAcquiringServicesCode'
        prices:
          type: array
          minItems: 4
          maxItems: 4
          items:
            $ref: '#/components/schemas/Price'
          example:
            - interval: 1_FAIXA # 1ST_RANGE
              value: '0.020300'
              customerRate: '0.500000'
            - interval: 2_FAIXA # 2ND_RANGE
              value: '0.030600'
              customerRate: '0.100000'
            - interval: 3_FAIXA # 3RD_RANGE
              value: '0.034300'
              customerRate: '0.300000'
            - interval: 4_FAIXA # 4TH_RANGE
              value: '0.246800'
              customerRate: '0.100000'
        chargingTriggerInfo:
          type: string
          minLength: 1
          maxLength: 200
          example: Recebimento através de transação de cartão. # Receipt through card transaction.
          description: |
            Description of the Charging Triggering Factor that affects the acquiring service.
        minimum:
          type: string
          minLength: 8
          maxLength: 8
          pattern: '^\d{1}\.\d{6}$'
          description: Minimum value
          example: '0.019800'
        maximum:
          type: string
          minLength: 8
          maxLength: 8
          pattern: '^\d{1}\.\d{6}$'
          description: Maximum value
          example: '0.019800'
      additionalProperties: false
    OpenDataResponseError:
      type: object
      required:
        - errors
      properties:
        errors:
          type: array
          minItems: 1
          maxItems: 13
          items:
            type: object
            required:
              - code
              - title
              - detail
            properties:
              code:
                description: Endpoint specific error code
                type: string
                pattern: '[\w\W\s]*'
                maxLength: 255
              title:
                description: Human-readable title for this specific error
                type: string
                pattern: '[\w\W\s]*'
                maxLength: 255
              detail:
                description: Human-readable description of this specific error
                type: string
                pattern: '[\w\W\s]*'
                maxLength: 2048
            additionalProperties: false
        meta:
          $ref: '#/components/schemas/OpenDataMeta'
      additionalProperties: false
  parameters:
    page:
      name: page
      in: query
      description: Page number that is being requested (the value of the first page is 1).
      schema:
        type: integer
        default: 1
        minimum: 1
        maximum: 2147483647
        format: int32
    pageSize:
      name: page-size
      in: query
      description: Total number of records per page.
      schema:
        type: integer
        default: 25
        minimum: 1
        format: int32
        maximum: 1000
  responses:
    OKResponseAcquiringServices:
      description: Acquiring operations data successfully obtained.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/OKResponseAcquiringServices'
    BadRequest:
      description: 'The request was malformed, omitting mandatory attributes, either in the payload or through URL attributes.'
      content:
        application/json; charset=utf-8:
          schema:
            $ref: '#/components/schemas/OpenDataResponseError'
    NotFound:
      description: The requested resource does not exist or has not been implemented
      content:
        application/json; charset=utf-8:
          schema:
            $ref: '#/components/schemas/OpenDataResponseError'
    MethodNotAllowed:
      description: The consumer attempted to access the resource with an unsupported method
      content:
        application/json; charset=utf-8:
          schema:
            $ref: '#/components/schemas/OpenDataResponseError'
    TooManyRequests:
      description: 'The operation was refused because too many requests were made within a certain period or the concurrent request limit was reached.'
      content:
        application/json; charset=utf-8:
          schema:
            $ref: '#/components/schemas/OpenDataResponseError'
    InternalServerError:
      description: An error occurred in the API gateway or microservice
      content:
        application/json; charset=utf-8:
          schema:
            $ref: '#/components/schemas/OpenDataResponseError'
    SiteIsOverloaded:
      description: 'The site is overloaded and the operation was refused because the global maximum TPS limit was reached at this time.'
      content:
        application/json; charset=utf-8:
          schema:
            type: object
            required:
              - errors
            properties:
              errors:
                type: array
                minItems: 1
                maxItems: 13
                items:
                  type: object
                  required:
                    - code
                    - title
                    - detail
                  properties:
                    code:
                      description: Endpoint specific error code
                      type: string
                      pattern: '[\w\W\s]*'
                      maxLength: 255
                    title:
                      description: Human-readable title for this specific error
                      type: string
                      pattern: '[\w\W\s]*'
                      maxLength: 255
                    detail:
                      description: Human-readable description of this specific error
                      type: string
                      pattern: '[\w\W\s]*'
                      maxLength: 2048
              meta:
                type: object
                description: Meta information regarding the requested API.
                required:
                  - requestDateTime
                properties:
                  requestDateTime:
                    description: 'Date and time of consultation, according to RFC-3339 specification, UTC format.'
                    type: string
                    maxLength: 20
                    format: date-time
                    example: '2021-05-21T08:30:00Z'
