
title: "Opus Open Finance"
description: "Documentação que descreve a Plataforma Opus Open Finance, incluindo integração e implantação"

url: ""
baseurl: "/Documentation"

default_lang: pt-br

langs:
  - pt-br
  - en
lang_names:
  pt-br: Português
  en: English

remote_theme: null  # Deve estar assim para usar o template local

theme: "just-the-docs"
just_the_docs:
  layout: default
  navigation_structure: true
  navigation:
    - text: "Plataforma Opus Open Finance"
      url: "/Documentation/pt-br/Open-Finance/OpenFinance/"
      lang: "pt-br"
    - text: "Opus Open Finance Platform"
      url: "/Documentation/en/Open-Finance/OpenFinance/"
      lang: "en"
  show_toc: true    # Exibe a barra lateral de navegação em todas as páginas
  toc_levels: 1..3  # Define os niveis de cabeçalho a serem exibidos (H1 a H3, ou #, ## e ###)
  sidebar:
    position: fixed # Mantém a barra lateral fixa
  search_enabled: true # Gera a caixa de pesquisa no alto das páginas do site.
  custom_js:
    - /assets/js/open-links.js
# remote_theme: "just-the-docs/just-the-docs"

include:            # Força o uso do layout default local em vez do remoto.
  - _layouts

footer_content: null

aux_links: null
  #
  #Template Repository: https://github.com/just-the-docs/just-the-docs-template
