openapi: 3.0.0
info:
  title: API Opus Commons - Integration Layer - Opus Open Finance Brasil
  description: |
    API de rotas que são gerais para o funcionamento dos conectores de todos os produtos.
    API com a rota que verifica se dado cliente possui uma conta na instituição financeira necessária para as rotas.
  version: 0.1.0-alpha
tags:
  - name: Common
    description: Operações necessárias para funcionamento geral dos conectores
paths:
  /check-account-holder:
    post:
      tags:
        - Common
      operationId: checkAccountHolderStatus
      summary: Verifica se documento consultado possui conta na detentora
      description: Método para verificar se a pessoa física ou jurídica mantém conta na instituição financeira
      parameters:
        - $ref: '#/components/parameters/x-brand-id'
        - $ref: '#/components/parameters/x-correlation-id'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CheckAccountHolderRequest'
      responses:
        '200':
          $ref: '#/components/responses/OKResponseCheckAccountHolder'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '405':
          $ref: '#/components/responses/MethodNotAllowed'
        '406':
          $ref: '#/components/responses/NotAcceptable'
        '422':
          $ref: '#/components/responses/UnprocessableEntity'
        '423':
          $ref: '#/components/responses/Locked'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/InternalServerError'
        '504':
          $ref: '#/components/responses/GatewayTimeout'
        '529':
          $ref: '#/components/responses/SiteIsOverloaded'
        default:
          $ref: '#/components/responses/Default'
components:
  schemas:
    CheckAccountHolderRequest:
      type: object
      description: Payload utilizado para verificação de correntista
      required:
        - data
      properties:
        data:
          type: object
          required:
            - loggedUserDocument
          properties:
            loggedUserDocument:
              type: string
              maxLength: 11
              description: Número do CPF do usuário.
              example:
                '11111111111'
              pattern: ^\d{11}$
            businessEntityDocument:
              type: string
              maxLength: 14
              description: Número do CNPJ da empresa.
              example:
                '11111111111111'
              pattern: ^\d{14}$
    CheckAccountHolderResponse:
      type: object
      required:
        - data
      properties:
        data:
          type: object
          description: Verifica se documento consultado possui conta na detentora
          required:
            - isAccountHolder
          properties:
            isAccountHolder:
              type: boolean
              description: Indica se documento consultado possui conta na detentora
              example: 'true'
          additionalProperties: false
      additionalProperties: false
    ResponseError:
      type: object
      required:
        - errors
      properties:
        errors:
          type: array
          minItems: 1
          maxItems: 13
          items:
            type: object
            required:
              - code
              - title
              - detail
            properties:
              code:
                description: Código de erro específico do endpoint
                type: string
                pattern: '[\w\W\s]*'
                maxLength: 255
              title:
                description: Título legível por humanos deste erro específico
                type: string
                pattern: '[\w\W\s]*'
                maxLength: 255
              detail:
                description: Descrição legível por humanos deste erro específico
                type: string
                pattern: '[\w\W\s]*'
                maxLength: 2048
  parameters:
    x-brand-id:
      name: x-brand-id
      in: header
      description: Identificador da marca reportada pelo participante do Open Finance
      required: true
      schema:
        type: string
        example: cbanco
        minLength: 1
        maxLength: 50
    x-correlation-id: 
      name: x-correlation-id
      in: header
      description: UUID que identifica o correlation ID da requisição realizada. Deve ser
            propagado para todas as chamadas feitas entre sistemas e logado sempre
            que possível para facilitar o trace de erros
      required: true
      schema:
        type: string
        format: uuid
        example: 97623ed1-4732-4bf2-8d4b-ae7aced5443b
  responses:
    OKResponseCheckAccountHolder:
      description: 'Verificou com sucesso se documento consultado possui conta na detentora'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/CheckAccountHolderResponse'
    BadRequest:
      description: 'A requisição foi malformada, omitindo atributos obrigatórios, seja no payload ou através de atributos na URL.'
      content:
        application/json; charset=utf-8:
          schema:
            $ref: '#/components/schemas/ResponseError'
    Forbidden:
      description: O token tem escopo incorreto ou uma política de segurança foi violada
      content:
        application/json; charset=utf-8:
          schema:
            $ref: '#/components/schemas/ResponseError'
    GatewayTimeout:
      description: GATEWAY TIMEOUT - A requisição não foi atendida dentro do tempo limite estabelecido
      content:
        application/json; charset=utf-8:
          schema:
            $ref: '#/components/schemas/ResponseError'
    InternalServerError:
      description: Ocorreu um erro no gateway da API ou no microsserviço
      content:
        application/json; charset=utf-8:
          schema:
            $ref: '#/components/schemas/ResponseError'
    Locked:
      description: Locked
      content:
        application/json; charset=utf-8:
          schema:
            $ref: '#/components/schemas/ResponseError'
    MethodNotAllowed:
      description: O consumidor tentou acessar o recurso com um método não suportado
      content:
        application/json; charset=utf-8:
          schema:
            $ref: '#/components/schemas/ResponseError'
    NotAcceptable:
      description: A solicitação continha um cabeçalho Accept diferente dos tipos de mídia permitidos ou um conjunto de caracteres diferente de UTF-8
      content:
        application/json; charset=utf-8:
          schema:
            $ref: '#/components/schemas/ResponseError'
    NotFound:
      description: O recurso solicitado não existe ou não foi implementado
      content:
        application/json; charset=utf-8:
          schema:
            $ref: '#/components/schemas/ResponseError'
    TooManyRequests:
      description: 'A operação foi recusada, pois muitas solicitações foram feitas dentro de um determinado período ou o limite global de requisições concorrentes foi atingido'
      content:
        application/json; charset=utf-8:
          schema:
            $ref: '#/components/schemas/ResponseError'
    Unauthorized:
      description: Cabeçalho de autenticação ausente/inválido ou token inválido
      content:
        application/json; charset=utf-8:
          schema:
            $ref: '#/components/schemas/ResponseError'
    UnprocessableEntity:
      description: 'A sintaxe da requisição esta correta, mas não foi possível processar as instruções presentes.'
      content:
        application/json; charset=utf-8:
          schema:
            $ref: '#/components/schemas/ResponseError'
    Default:
      description: Erro inesperado.
      content:
        application/json; charset=utf-8:
          schema:
            $ref: '#/components/schemas/ResponseError'
    SiteIsOverloaded:
      description: 'O site está sobrecarregado e a operação foi recusada, pois foi atingido o limite máximo de TPS global, neste momento.'
      content:
        application/json; charset=utf-8:
          schema:
            $ref: '#/components/schemas/ResponseError'
